### ISSUE TITLE
Misc TODO

### ISSUE THREAD

**Issue by Xiphoseer** [Xiphoseer/lu-explorer#73]
* [x] Figure out why some MissionTasks are null?
* [ ] What does 'taskParam1' for an ObtainItem task?
* [ ] Add locStatus, localized to mission tasks
* [ ] Add links to racing mission tasks
* [ ] Figure out what the ids in quickbuild tasks are
* [x] Investigate QuickBuild vs Minigame in mission 1434
* [x] Investigate emote rewards in Mission 1750 - fixed by #75
* [ ] Mission Texts offerNPCIcon
* [x] display MissionTasks localization (e.g. Mission 282)
